package com.tencent.qqnt.kernel.nativeinterface;

import java.util.ArrayList;

public class RecentContactInfo {
    //public ArrayList<MsgAbstractElement> abstractContent;
    public Integer anonymousFlag;
    public int atType;
    public String avatarPath;
    public String avatarUrl;
    public long c2cClientMsgSeq;
    public int chatType;
    public long contactId;
    //public ArrayList<MsgAbstractElement> draft;
    public byte draftFlag;
    public long draftTime;
    //public ArrayList<RecentContactExtAttr> extAttrs;
    public byte[] extBuffer;
    //public GuildContactInfo guildContactInfo;
    public int hiddenFlag;
    public String id;
    public boolean isBeat;
    public boolean isBlock;
    public boolean isMsgDisturb;
    public boolean isOnlineMsg;
    public int keepHiddenFlag;
    //public ArrayList<SpecificEventTypeInfoInMsgBox> listOfSpecificEventTypeInfosInMsgBox;
    //public HashMap<LiteBusinessType, String> liteBusiness;
    public String memberName;
    public long msgId;
    public long msgRandom;
    public long msgSeq;
    public long msgTime;
    public long msgUid;
    public ArrayList<RecentContactInfo> nestedChangedList;
    public ArrayList<Long> nestedSortedContactList;
    public int notifiedType;
    public String peerName;
    public String peerUid;
    public long peerUin;
    public String remark;
    public String sendMemberName;
    public String sendNickName;
    public String sendRemarkName;
    public int sendStatus;
    public String senderUid;
    public long senderUin;
    public int sessionType;
    public long shieldFlag;
    public long sortField;
    public byte specialCareFlag;
    public byte topFlag;
    public long topFlagTime;
    public int unreadChatCnt;
    public long unreadCnt;
    public long unreadFlag;
    //public VASRecentContactMsgElement vasMsgInfo;
    //public VASPersonalElement vasPersonalInfo;
}
